; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PhotoNest Cutout"
#define MyAppNameZh "Cutout"
#define MyAppVersion "3.10.2.9"
#define MyAppPublisher "PhotoNest"
#define MyAppURL "https://www.photonest.io/"
#define MyAppExeName "cutout.exe"
#define SourceMain ".."
#define OutputPath "_outputPath_"
#define MyAppId "PhotoNest Cutout"
#define srcexe "photonest-cutout-setup-3.10.2.9.exe"


[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
VersionInfoVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
;DefaultDirName={#MyAppName}
DefaultDirName={code:GetDefaultInstallRoot}

DefaultGroupName=PhotoNest
LicenseFile=.\resources\agreement.rtf
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir={#OutputPath}
OutputBaseFilename=photonest-cutout-setup-3.10.2.9
Compression=lzma
SolidCompression=yes
WizardStyle=modern


;DisableReadyPage=yes
DisableProgramGroupPage=yes
;DirExistsWarning=no
;DisableDirPage=yes
ShowLanguageDialog=no
LanguageDetectionMethod=uilanguage
CloseApplications=no

[Languages]
Name: de; MessagesFile: "compiler:Languages\German.isl"
Name: en; MessagesFile: "compiler:Default.isl"
Name: es; MessagesFile: "compiler:Languages\Spanish.isl"
Name: fr; MessagesFile: "compiler:Languages\French.isl"
Name: it; MessagesFile: "compiler:Languages\Italian.isl"
Name: ja; MessagesFile: "compiler:Languages\Japanese.isl"
Name: ru; MessagesFile: "compiler:Languages\Russian.isl"
Name: zh; MessagesFile: "compiler:Languages\ChineseSimp.isl"


[Messages]
de.BeveledLabel=German
en.BeveledLabel=English
es.BeveledLabel=Spanish
fr.BeveledLabel=French
it.BeveledLabel=Italian
ja.BeveledLabel=Japanese
ru.BeveledLabel=Russian
zh.BeveledLabel=Chinese (Simplified)

[CustomMessages]
de.ButtonInstall=&Aktualisierung
de.ReadyLabel2b=Klicken Sie auf "Aktualisierung", um mit der Installation zu beginnen.
en.ButtonInstall=&Upgrade
en.ReadyLabel2b=Click Upgrade to continue with the installation.
es.ButtonInstall=&Actualización
es.ReadyLabel2b=Haga clic en Actualización para continuar con el proceso.
fr.ButtonInstall=&Mise à jour
fr.ReadyLabel2b=Valitse "Mise à jour" jatkaaksesi asentamista.
it.ButtonInstall=&Aggiornamento
it.ReadyLabel2b=Per procedere con l'installazione seleziona "Aggiornamento".
ja.ButtonInstall=アップグレード(&I)
ja.ReadyLabel2b=インストールを続行するには「アップグレード」をクリックしてください。
ru.ButtonInstall=&Обновление
ru.ReadyLabel2b=Нажмите "Обновление", чтобы продолжить.
zh.ButtonInstall=升级
zh.ReadyLabel2b=点击“升级”继续安装。



[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[Files]
Source: "{#SourceMain}\bin\cutout.exe"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs 

Source: "{#SourceMain}\bin\photol.dll"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs    
Source: "{#SourceMain}\bin\photol.dat"; DestDir: "{app}\bin\locales"; Flags: onlyifdoesntexist    
Source: "{#SourceMain}\bin\model\*"; DestDir: "{app}\bin\model"; Flags: ignoreversion recursesubdirs 
Source: "{#SourceMain}\bin\help\cutout.html"; DestDir: "{app}\bin\help"; Flags: ignoreversion recursesubdirs 
;Source: "{#SourceMain}\bin\locales\paint\*"; DestDir: "{app}\bin\locales\paint"; Flags: ignoreversion recursesubdirs 

Source: "{#SourceMain}\extension\*"; DestDir: "{app}\extension"; Flags: ignoreversion recursesubdirs createallsubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: ".\resources\ins.dll"; DestDir: {tmp}; Flags: dontcopy solidbreak 

[Dirs]
;Name: "{userappdata}\Local\PhotoNest"

[Icons]

Name: "{commondesktop}\PhotoNest Cutout"; Filename: "{app}\bin\cutout.exe"; Tasks: desktopicon
Name: "{group}\{#MyAppNameZh}"; Filename: "{app}\bin\cutout.exe"




[Registry]
; Start "Software\My Company\My Program" keys under HKEY_CURRENT_USER
; and HKEY_LOCAL_MACHINE. The flags tell it to always delete the
; "My Program" keys upon uninstall, and delete the "My Company" keys
; if there is nothing left in them.

Root: HKCR; Subkey: ".jpg\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.pic"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".jpeg\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.pic"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".png\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.pic"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".bmp\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.pic"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".webp\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.pic"; ValueData: ""; Flags: uninsdeletevalue


Root: HKCR; Subkey: "PhotoNest.pic"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PhotoNest.pic\shell"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PhotoNest.pic\DefaultIcon"; ValueType: string; ValueData: "{app}\bin\cutout.exe,-2"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PhotoNest.pic\shell\open"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "PhotoNest Cutout"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PhotoNest.pic\shell\open\command"; ValueType: string; ValueData: """{app}\bin\cutout.exe"" ""%1"""; Flags: uninsdeletekey


Root: HKLM; Subkey: "Software\Classes\.jpg\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.pic"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\.jpeg\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.pic"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\.png\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.pic"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\.bmp\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.pic"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\.webp\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.pic"; ValueData: ""; Flags: uninsdeletevalue

Root: HKLM; Subkey: "Software\Classes\PhotoNest.pic"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\PhotoNest.pic\shell"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\PhotoNest.pic\DefaultIcon"; ValueType: string; ValueData: "{app}\bin\cutout.exe,-2"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\PhotoNest.pic\shell\open"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "PhotoNest Cutout"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\PhotoNest.pic\shell\open\command"; ValueType: string; ValueData: """{app}\bin\cutout.exe"" ""%1"""; Flags: uninsdeletekey


[Run]
Filename: "{app}\bin\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
;Type: files; Name: "{localappdata}\PhotoNest\Cutout\prof.ini"

[Code]
// for dll

function ShowLangDialog(hWnd: Integer; ty: Integer; lpText: String): Integer; external 'ShowLangDialog@files:ins.dll stdcall setuponly';
function SelectLangIni(ty: Integer; lpText: String): Integer; external 'SelectLangIni@files:ins.dll stdcall setuponly';
function CopySample(ty: Integer; lpDir: String): Integer; external 'CopySample@files:ins.dll stdcall setuponly';
function GetDriveType(lpRootPathName:AnsiString): Longint; external 'GetDriveTypeA@kernel32.dll stdcall';

var bExist: Boolean;
	uicmd: String;
	finished: String;

function GetDefaultInstallRoot(Param: String): String; 
var s: String; 
	nn:Integer;
begin  
	if (bExist = true) then begin
		s:=uicmd;
		StringChange(s, '\unins000.exe', '');  
		StringChange(s, '"', ''); 
		Result := s;	
	end else begin	
		nn:=GetDriveType('D:/');
		//DRIVE_FIXED 3
		if(nn=3)then begin
			Result := 'D:\PhotoNest\Cutout';
		end else begin
			Result := 'C:\PhotoNest\Cutout';  
		end
	end;
end;  

function InitializeSetup(): Boolean;
var Language: string;
	ret: Integer; 
	appWnd: HWND;
begin
	finished := '';
	Language := ExpandConstant('{param:LANG}');
	bExist := RegQueryStringValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PhotoNest Cutout_is1', 'UninstallString', uicmd);
	if (bExist = True) then begin
		if Language = '' then begin
			SelectLangIni(0, ExpandConstant('{srcexe}'));
			Result := False;
			Exit;
		end else begin
			result := True;
		end;
	end else begin
		if Language = '' then begin
			appWnd :=  FindWindowByWindowName('Setup');
			ret:= ShowLangDialog(appWnd, 0, ExpandConstant('{srcexe}'));
			Result := False;
			Exit;
		end else begin
			Result := True;  
		end;
	end;		
end;
    
procedure DeinitializeSetup();
var
	FileName: String;
	s5: String;
	b:Boolean;
begin
	if finished = '1' then begin
		b := False;//DirExists(s5);
		if b = False then begin
			CopySample(0, '');
		end;
	end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
	if CurPageID = wpReady then begin
		if (bExist = True) then begin
			WizardForm.NextButton.Caption := CustomMessage('ButtonInstall');
			WizardForm.ReadyLabel.Caption := CustomMessage('ReadyLabel2b');
		end;
	end else if CurPageID = wpFinished then begin
		finished := '1';
	end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var ErrorCode: Integer;
begin
	if CurPageID = wpReady then begin
		if (bExist = True) then begin
			ShellExec('open','taskkill.exe','/f /im {#MyAppExeName}','',SW_HIDE,ewWaitUntilTerminated,ErrorCode);
		end;
	end;
	result := True;
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
	if PageID = wpSelectTasks then begin
		if (bExist = True) then begin
			result := True;
		end;
	end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var ErrorCode: Integer;
	szCode: String;
	appWnd: HWND;
begin
	if CurUninstallStep = usAppMutexCheck then begin
		ShellExec('open','taskkill.exe','/f /im {#MyAppExeName}','',SW_HIDE,ewWaitUntilTerminated,ErrorCode);
		//SetIniString('section', 'language', '', ExpandConstant('{localappdata}\PhotoNest\Cutout\prof.ini')); 
//		RegQueryStringValue(HKEY_CURRENT_USER, 'SOFTWARE\OpenCV\HighGUI\Windows\ZK1', 'wo3', szCode);
//		if (szCode <> '') then begin
//			RegDeleteValue(HKEY_CURRENT_USER, 'SOFTWARE\OpenCV\HighGUI\Windows\ZK1', 'wo3');
//			RegDeleteValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\PhotoNest\Cutout', 'i3');
//		end;
	end;
end;