; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PhotoNest"
#define MyAppNameZh "PhotoNest"
#define MyAppVersion "3.10.2.9"
#define MyAppPublisher "PhotoNest"
#define MyAppURL "https://www.photonest.io/"
#define MyAppExeName "nest1.exe"
#define SourceMain ".."
#define OutputPath "_outputPath_"
#define MyAppId "PhotoNest"
#define srcexe "photonest-setup-3.10.2.9.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
VersionInfoVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
;DefaultDirName={#MyAppName}
DefaultDirName={code:GetDefaultInstallRoot}

DefaultGroupName=PhotoNest
LicenseFile=.\resources\agreement.rtf
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir={#OutputPath}
OutputBaseFilename=photonest-setup-3.10.2.9
Compression=lzma
SolidCompression=yes
WizardStyle=modern

;DisableReadyPage=yes
DisableProgramGroupPage=yes
;DirExistsWarning=no
;DisableDirPage=yes
ShowLanguageDialog=no
LanguageDetectionMethod=uilanguage
CloseApplications=no

[Languages]
Name: de; MessagesFile: "compiler:Languages\German.isl"
Name: en; MessagesFile: "compiler:Default.isl"
Name: es; MessagesFile: "compiler:Languages\Spanish.isl"
Name: fr; MessagesFile: "compiler:Languages\French.isl"
Name: it; MessagesFile: "compiler:Languages\Italian.isl"
Name: ja; MessagesFile: "compiler:Languages\Japanese.isl"
Name: ru; MessagesFile: "compiler:Languages\Russian.isl"
Name: zh; MessagesFile: "compiler:Languages\ChineseSimp.isl"


[Messages]
de.BeveledLabel=German
en.BeveledLabel=English
es.BeveledLabel=Spanish
fr.BeveledLabel=French
it.BeveledLabel=Italian
ja.BeveledLabel=Japanese
ru.BeveledLabel=Russian
zh.BeveledLabel=Chinese (Simplified)

[CustomMessages]
de.ButtonInstall=&Aktualisierung
de.ReadyLabel2b=Klicken Sie auf "Aktualisierung", um mit der Installation zu beginnen.
en.ButtonInstall=&Upgrade
en.ReadyLabel2b=Click Upgrade to continue with the installation.
es.ButtonInstall=&Actualización
es.ReadyLabel2b=Haga clic en Actualización para continuar con el proceso.
fr.ButtonInstall=&Mise à jour
fr.ReadyLabel2b=Valitse "Mise à jour" jatkaaksesi asentamista.
it.ButtonInstall=&Aggiornamento
it.ReadyLabel2b=Per procedere con l'installazione seleziona "Aggiornamento".
ja.ButtonInstall=アップグレード(&I)
ja.ReadyLabel2b=インストールを続行するには「アップグレード」をクリックしてください。
ru.ButtonInstall=&Обновление
ru.ReadyLabel2b=Нажмите "Обновление", чтобы продолжить.
zh.ButtonInstall=升级
zh.ReadyLabel2b=点击“升级”继续安装。



[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[Files]
Source: "{#SourceMain}\bin\nest1.exe"; DestDir: "{app}\bin"; DestName:"nest1.exe"; Flags: ignoreversion recursesubdirs 
Source: "{#SourceMain}\bin\paint.exe"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs 
Source: "{#SourceMain}\bin\viewer.exe"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs 
Source: "{#SourceMain}\bin\inscl.exe"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs 

Source: "{#SourceMain}\bin\*.dll"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs       
Source: "{#SourceMain}\bin\*.pak"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs 
Source: "{#SourceMain}\bin\icudtl.dat"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs 
Source: "{#SourceMain}\bin\*.bin"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs 
Source: "{#SourceMain}\bin\*.json"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs 

Source: "{#SourceMain}\bin\locales\album\*"; DestDir: "{app}\bin\locales\album"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceMain}\bin\locales\paint\*"; DestDir: "{app}\bin\locales\paint"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceMain}\bin\locales\en-US.pak"; DestDir: "{app}\bin\locales"; Flags: ignoreversion recursesubdirs createallsubdirs
;Source: "{#SourceMain}\bin\swiftshader\*"; DestDir: "{app}\bin\swiftshader"; Flags: ignoreversion recursesubdirs 
Source: "{#SourceMain}\bin\model\*"; DestDir: "{app}\bin\model"; Flags: ignoreversion recursesubdirs 
Source: "{#SourceMain}\bin\help\credits.html"; DestDir: "{app}\bin\help"; Flags: ignoreversion recursesubdirs 

Source: "{#SourceMain}\extension\*"; DestDir: "{app}\extension"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#SourceMain}\bg\*"; DestDir: "{app}\bg"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceMain}\templ\*"; DestDir: "{app}\templ"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "{#SourceMain}\db\photo1.db"; DestDir: "{app}\data1\_db"; Flags: onlyifdoesntexist uninsneveruninstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: ".\resources\ins.dll"; DestDir: {tmp}; Flags: dontcopy solidbreak 

[Dirs]
;Name: "{app}\bin\locales"
Name: "{app}\data1\_temp"
Name: "{app}\data1\_thumb"
Name: "{app}\data1\_data"
Name: "{app}\data1\_train"
Name: "{app}\data1\_train\_face"
Name: "{app}\data1\_train\_temp"
Name: "{app}\data1\_train\_model"

[Icons]

Name: "{commondesktop}\PhotoNest"; Filename: "{app}\bin\nest1.exe"; Tasks: desktopicon
Name: "{group}\{#MyAppNameZh}"; Filename: "{app}\bin\nest1.exe"


[Registry]
; Start "Software\My Company\My Program" keys under HKEY_CURRENT_USER
; and HKEY_LOCAL_MACHINE. The flags tell it to always delete the
; "My Program" keys upon uninstall, and delete the "My Company" keys
; if there is nothing left in them.

Root: HKCR; Subkey: ".jpg\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.vr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".jpeg\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.vr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".png\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.vr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".bmp\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.vr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".gif\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.vr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".mp3\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.mp4"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".mp4\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.mp4"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: ".webp\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.vr"; ValueData: ""; Flags: uninsdeletevalue


Root: HKCR; Subkey: "PhotoNest.vr"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PhotoNest.vr\shell"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PhotoNest.vr\DefaultIcon"; ValueType: string; ValueData: "{app}\bin\viewer.exe,-2"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PhotoNest.vr\shell\open"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "PhotoNest Viewer"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PhotoNest.vr\shell\open\command"; ValueType: string; ValueData: """{app}\bin\viewer.exe"" ""%1"""; Flags: uninsdeletekey


Root: HKCR; Subkey: "PhotoNest.mp4"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PhotoNest.mp4\shell"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PhotoNest.mp4\DefaultIcon"; ValueType: string; ValueData: "{app}\bin\viewer.exe,-1"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PhotoNest.mp4\shell\open"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "PhotoNest Viewer"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PhotoNest.mp4\shell\open\command"; ValueType: string; ValueData: """{app}\bin\viewer.exe"" ""%1"""; Flags: uninsdeletekey



Root: HKLM; Subkey: "Software\Classes\.jpg\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.vr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\.jpeg\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.vr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\.png\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.vr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\.bmp\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.vr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\.gif\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.vr"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\.mp3\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.mp4"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\.mp4\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.mp4"; ValueData: ""; Flags: uninsdeletevalue
Root: HKLM; Subkey: "Software\Classes\.webp\OpenWithProgids"; ValueType: string; ValueName: "PhotoNest.vr"; ValueData: ""; Flags: uninsdeletevalue

Root: HKLM; Subkey: "Software\Classes\PhotoNest.vr"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\PhotoNest.vr\shell"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\PhotoNest.vr\DefaultIcon"; ValueType: string; ValueData: "{app}\bin\viewer.exe,-2"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\PhotoNest.vr\shell\open"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "PhotoNest Viewer"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\PhotoNest.vr\shell\open\command"; ValueType: string; ValueData: """{app}\bin\viewer.exe"" ""%1"""; Flags: uninsdeletekey


Root: HKLM; Subkey: "Software\Classes\PhotoNest.mp4"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\PhotoNest.mp4\shell"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\PhotoNest.mp4\DefaultIcon"; ValueType: string; ValueData: "{app}\bin\viewer.exe,-1"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\PhotoNest.mp4\shell\open"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "PhotoNest Viewer"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Classes\PhotoNest.mp4\shell\open\command"; ValueType: string; ValueData: """{app}\bin\viewer.exe"" ""%1"""; Flags: uninsdeletekey

;Root: HKCR; Subkey: "Applications\nest1.exe"; Flags: uninsdeletekey


[Run]
Filename: "{app}\bin\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]

[UninstallRun]

[Code]
// for dll

function ShowLangDialog(hWnd: Integer; ty: Integer; lpText: String): Integer; external 'ShowLangDialog@files:ins.dll stdcall setuponly';
function SelectLangIni(ty: Integer; lpText: String): Integer; external 'SelectLangIni@files:ins.dll stdcall setuponly';
function CopySample(ty: Integer; lpDir: String): Integer; external 'CopySample@files:ins.dll stdcall setuponly';
function GetDriveType(lpRootPathName:AnsiString): Longint; external 'GetDriveTypeA@kernel32.dll stdcall';

var bExist: Boolean;
	uicmd: String;
	finished: String;

function GetDefaultInstallRoot(Param: String): String; 
var s: String; 
	nn:Integer;
begin  
	if (bExist = true) then begin
		s:=uicmd;
		StringChange(s, '\unins000.exe', '');  
		StringChange(s, '"', ''); 
		Result := s;	
	end else begin	
		nn:=GetDriveType('D:/');
		//DRIVE_FIXED 3
		if(nn=3)then begin
			Result := 'D:\PhotoNest\Nest1';
		end else begin
			Result := 'C:\PhotoNest\Nest1';  
		end
	end;
end;  

function InitializeSetup(): Boolean;
var Language: string;
	ret: Integer; 
	appWnd: HWND;
begin
	finished := '';
	Language := ExpandConstant('{param:LANG}');
	bExist := RegQueryStringValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PhotoNest_is1', 'UninstallString', uicmd);
	if (bExist = True) then begin
		if Language = '' then begin
			SelectLangIni(1, ExpandConstant('{srcexe}'));
			Result := False;
			Exit;
		end else begin
			result := True;
		end;
	end else begin
		if Language = '' then begin
			appWnd :=  FindWindowByWindowName('Setup');
			ret:= ShowLangDialog(appWnd, 1, ExpandConstant('{srcexe}'));
			Result := False;
			Exit;
		end else begin
			Result := True;  
		end;
	end;		
end;

  
procedure DeinitializeSetup();
var
	FileName: String;
	s5: String;
	b:Boolean;
begin
	if finished = '1' then begin
		FileName:=ExpandConstant('{app}');
		s5 := FileName + '\sample';
		b := False;//DirExists(s5);
		if b = False then begin
			CopySample(1, FileName);
		end;
	end;
end;
  
procedure CurPageChanged(CurPageID: Integer);
begin
	if CurPageID = wpReady then begin
		if (bExist = True) then begin
			WizardForm.NextButton.Caption := CustomMessage('ButtonInstall');
			WizardForm.ReadyLabel.Caption := CustomMessage('ReadyLabel2b');
		end;
	end else if CurPageID = wpFinished then begin
		finished := '1';
	end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var ErrorCode: Integer;
begin
	if CurPageID = wpReady then begin
		if (bExist = True) then begin
			ShellExec('open','taskkill.exe','/f /im {#MyAppExeName}','',SW_HIDE,ewWaitUntilTerminated,ErrorCode);
		end;
	end;
	result := True;
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
	if PageID = wpSelectTasks then begin
		if (bExist = True) then begin
			result := True;
		end;
	end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var ErrorCode: Integer;
	szResponse: String;
	szCode: String;
	appWnd: HWND;
begin
	if CurUninstallStep = usAppMutexCheck then begin
		ShellExec('open','taskkill.exe','/f /im {#MyAppExeName}','',SW_HIDE,ewWaitUntilTerminated,ErrorCode);
		szResponse:=ExpandConstant('{app}\bin\inscl.exe');
		appWnd :=  FindWindowByWindowName('Uninstall');
		ShellExec('open',szResponse,IntToStr(appWnd) + ' nest1','',SW_SHOW,ewWaitUntilTerminated,ErrorCode);
		if ErrorCode=200 then begin   
			Abort;
		end else begin
		end; 
	end;
end;